
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Employee')
BEGIN
CREATE TABLE Employee (
 Id INT IDENTITY(1,1) PRIMARY KEY,
 Name VARCHAR(250) NOT NULL,
 Address VARCHAR(500),
 DeptId Int FOREIGN KEY  References Department(Id)
)
END

IF NOT EXISTS(SELECT  TOP 1 * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='Department')
BEGIN
 CREATE TABLE Department (
  Id INT IDENTITY(1,1) PRIMARY KEY,
  Name VARCHAR(250)
 )
END